Repository airlift/airlift, pull requests merged in 2024-10, with the labels that each got.

#1293 Disable TLS renegotiation
  http-server/src/main/java/io/airlift/http/server/ReloadableSslContextFactoryProvider.java
Labels: improvement

#1304 Remove io.airlift.testing.Assertions class
  bootstrap/src/test/java/io/airlift/bootstrap/TestBootstrap.java
  concurrent/src/test/java/io/airlift/concurrent/TestAsyncSemaphore.java
  concurrent/src/test/java/io/airlift/concurrent/TestMoreFutures.java
  configuration/src/test/java/io/airlift/configuration/ProblemsTest.java
  configuration/src/test/java/io/airlift/configuration/testing/TestConfigAssertions.java
  discovery/src/test/java/io/airlift/discovery/client/TestCachingServiceSelector.java
  event/src/test/java/io/airlift/event/client/TestEventValidation.java
  http-client/src/test/java/io/airlift/http/client/AbstractHttpClientTest.java
  http-client/src/test/java/io/airlift/http/client/TestHttpClientBinder.java
  http-client/src/test/java/io/airlift/http/client/testing/TestTestingHttpClient.java
  http-server/src/test/java/io/airlift/http/server/TestHttpServerProvider.java
  http-server/src/test/java/io/airlift/http/server/testing/AbstractTestTestingHttpServer.java
  jmx-http/src/test/java/io/airlift/jmx/TestMBeanResource.java
  jmx/src/test/java/io/airlift/jmx/testing/TestTestingJmxModule.java
  node/src/test/java/io/airlift/node/TestNodeInfo.java
  node/src/test/java/io/airlift/node/TestNodeModule.java
  node/src/test/java/io/airlift/node/testing/TestTestingNodeModule.java
  sample-server/src/test/java/io/airlift/sample/TestPersonsResource.java
  sample-server/src/test/java/io/airlift/sample/TestServer.java
  security-jwks/src/test/java/io/airlift/security/jwks/TestJwksDecoder.java
  stats/src/test/java/io/airlift/stats/TestJmxGcMonitor.java
  stats/src/test/java/io/airlift/stats/TimedStatTest.java
  testing/src/main/java/io/airlift/testing/Assertions.java
  testing/src/test/java/io/airlift/testing/TestAssertions.java
  testing/src/test/java/io/airlift/testing/TestEquivalenceTester.java
  testing/src/test/java/io/airlift/testing/TestValidationAssertions.java
Labels: breaking, cleanup

#1300 Improve JsonSubType so that mappers on base type serialize correctly
  json/src/main/java/io/airlift/json/JsonSubType.java
  json/src/test/java/io/airlift/json/subtype/TestJsonSubType.java
Labels: improvement

#1309 Simplify SetThreadName
  concurrent/src/main/java/io/airlift/concurrent/SetThreadName.java
Labels: improvement, breaking
