Repository airlift/airlift, pull requests merged in 2024-08, with the labels that each got.

#1182 Seal BodyGenerator - disallow custom implementations
  http-client/src/main/java/io/airlift/http/client/BodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/ByteBufferBodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/FileBodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/JsonBodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/StaticBodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/StreamingBodyGenerator.java
  http-client/src/main/java/io/airlift/http/client/jetty/JettyHttpClient.java
  http-client/src/test/java/io/airlift/http/client/AbstractHttpClientTest.java
  jaxrs-testing/src/main/java/io/airlift/jaxrs/testing/JaxrsTestingHttpProcessor.java
Labels: improvement

#1237 Enable RESPONSE_SET_STATUS_OVER_SEND_ERROR for jax-rs container
  jaxrs/src/main/java/io/airlift/jaxrs/JaxrsModule.java
Labels: enhancement, improvement

#1238 Remove deprecated CacheStatsMBean
  jmx/src/main/java/io/airlift/jmx/CacheStatsMBean.java
Labels: breaking

#1257 Support case insensitivity
  http-client/src/main/java/io/airlift/http/client/Request.java
  http-client/src/test/java/io/airlift/http/client/TestRequest.java
Labels: improvement
