Repository airlift/airlift, pull requests merged in 2025-01, with the labels that each got.

#1353 Set default encoding for the error handler in HTTP module
  http-server/src/main/java/io/airlift/http/server/HttpServer.java
Labels: improvement

#1352 Add message to the UnexpectedResponseException.toString() output
  http-client/src/main/java/io/airlift/http/client/UnexpectedResponseException.java
Labels: improvement

#1316 Remove auth preserving request
  http-client/src/main/java/io/airlift/http/client/Request.java
  http-client/src/main/java/io/airlift/http/client/jetty/AuthorizationPreservingHttpClient.java
  http-client/src/main/java/io/airlift/http/client/jetty/JettyHttpClient.java
  http-client/src/test/java/io/airlift/http/client/AbstractHttpClientTest.java
  http-client/src/test/java/io/airlift/http/client/TestRequest.java
  http-client/src/test/java/io/airlift/http/client/TestRequestBuilder.java
Labels: breaking, cleanup

#1357 Remove vestigial jackson version definition
  json/src/test/java/io/airlift/json/TestJsonCodec.java
  pom.xml
Labels: cleanup

#1361 Add streaming read methods to JsonCodec
  discovery/src/main/java/io/airlift/discovery/client/HttpDiscoveryLookupClient.java
  discovery/src/main/java/io/airlift/discovery/client/ServiceInventory.java
  http-client/src/main/java/io/airlift/http/client/DefaultingJsonResponseHandler.java
  json/src/main/java/io/airlift/json/JsonCodec.java
  json/src/test/java/io/airlift/json/ImmutablePerson.java
  json/src/test/java/io/airlift/json/Person.java
  json/src/test/java/io/airlift/json/TestJsonCodec.java
  json/src/test/java/io/airlift/json/Vehicle.java
Labels: enhancement

#1364 Remove trace token leftovers
  pom.xml
  trace-token/pom.xml
  trace-token/src/main/java/io/airlift/tracetoken/TraceTokenManager.java
  trace-token/src/main/java/io/airlift/tracetoken/TraceTokenModule.java
  trace-token/src/test/java/io/airlift/tracetoken/TestTraceTokenManager.java
Labels: cleanup

#1365 Run CI tests on arm
  .github/workflows/ci.yml
Labels: improvement
