Repository airlift/airlift, pull requests merged in 2025-02, with the labels that each got.

#1373 Expand @Deprecated warning rendering in configuration
  configuration/src/main/java/io/airlift/configuration/ConfigurationFactory.java
  configuration/src/test/java/io/airlift/configuration/TestConfigurationFactory.java
Labels: enhancement, improvement

#1375 Remove JacksonMapper and introduce JsonParsingException
  jaxrs/src/main/java/io/airlift/jaxrs/JacksonMapper.java
  jaxrs/src/main/java/io/airlift/jaxrs/JaxrsModule.java
  jaxrs/src/main/java/io/airlift/jaxrs/JsonMapper.java
  jaxrs/src/main/java/io/airlift/jaxrs/JsonParsingException.java
  jaxrs/src/test/java/io/airlift/jaxrs/TestJsonMapper.java
Labels: improvement, breaking

#1376 Add withX to Bootstrap
  bootstrap/src/main/java/io/airlift/bootstrap/Bootstrap.java
Labels: enhancement, improvement

#1380 Expose binding to SdkTracer
  tracing/src/main/java/io/airlift/tracing/OpenTelemetryModule.java
Labels: enhancement, improvement

#1386 Update Airlift and CI to JDK 22 baseline
  .github/workflows/ci.yml
  pom.xml
Labels: breaking

#1389 Add JSON format support to console logger
  log-manager/src/main/java/io/airlift/log/Logging.java
  log-manager/src/main/java/io/airlift/log/LoggingConfiguration.java
  log-manager/src/main/java/io/airlift/log/OutputStreamHandler.java
  log-manager/src/test/java/io/airlift/log/TestLoggingConfiguration.java
  log-manager/src/test/java/io/airlift/log/TestOutputStreamHandler.java
Labels: improvement

#1235 Log warning when Major GC fails to recover significant memory
  stats/src/main/java/io/airlift/stats/JmxGcMonitor.java
  stats/src/test/java/io/airlift/stats/GcMonitorTester.java
  stats/src/test/java/io/airlift/stats/TestJmxGcMonitor.java
Labels: improvement

#1384 Use SdkTracerProvider to create a Tracer
  tracing/src/main/java/io/airlift/tracing/OpenTelemetryModule.java
Labels: cleanup

#1390 Make command line log output colored if supported
  log-manager/src/main/java/io/airlift/log/Format.java
  log-manager/src/main/java/io/airlift/log/Logging.java
  log-manager/src/main/java/io/airlift/log/StaticFormatter.java
  log-manager/src/main/java/io/airlift/log/TerminalColors.java
Labels: enhancement, improvement

#1378 Add 'Did you mean' to the unused configuration properties
  bootstrap/pom.xml
  bootstrap/src/main/java/io/airlift/bootstrap/Bootstrap.java
  bootstrap/src/main/java/io/airlift/bootstrap/FuzzyMatcher.java
  bootstrap/src/test/java/io/airlift/bootstrap/TestBootstrap.java
  bootstrap/src/test/java/io/airlift/bootstrap/TestFuzzyMatcher.java
  configuration/src/main/java/io/airlift/configuration/ConfigurationFactory.java
Labels: enhancement, improvement

#1377 Disable ENV interpolation during bootstrap
  bootstrap/pom.xml
  bootstrap/src/main/java/io/airlift/bootstrap/Bootstrap.java
  bootstrap/src/test/java/io/airlift/bootstrap/TestBootstrap.java
Labels: breaking

#1393 Enable colors for console
  log-manager/src/main/java/io/airlift/log/Logging.java
Labels: enhancement, improvement

#1400 Improve license section in POM
  pom.xml
Labels: improvement
